name: 'create-release'
description: 'Github Action for creating Github Releases'
author: 'Conventional Actions'
inputs:
  body:
    description: 'Noteworthy description of changes in release'
    required: false
  body_path:
    description: 'Path to load noteworthy description of changes in release from'
    required: false
  name:
    description: 'Gives the release a custom name. Defaults to tag name'
    required: false
  tag_name:
    description: 'Gives a tag name. Defaults to github.ref'
    required: false
    default: ${{ github.ref }}
  draft:
    description: 'Creates a draft release. Defaults to false'
    required: false
    default: 'false'
  prerelease:
    description: 'Identify the release as a prerelease. Defaults to false'
    required: false
    default: 'false'
  files:
    description: 'Newline-delimited list of path globs for asset files to upload'
    required: false
  artifacts:
    description: 'Newline-delimited list of artifact globs to upload'
    required: false
  fail_on_unmatched_files:
    description: 'Fails if any of the `files` globs match nothing. Defaults to false'
    required: false
    default: 'false'
  repository:
    description: 'Repository to make releases against, in <owner>/<repo> format'
    required: false
  token:
    description: 'Authorized secret GitHub Personal Access Token. Defaults to github.token'
    required: false
    default: ${{ github.token }}
  target_commitish:
    description: 'Commitish value that determines where the Git tag is created from. Can be any branch or commit SHA.'
    required: false
  generate_release_notes:
    description: 'Whether to automatically generate the name and body for this release. If name is specified, the specified name will be used; otherwise, a name will be automatically generated. If body is specified, the body will be pre-pended to the automatically generated notes.'
    required: false
    default: 'true'
  append_body:
    description: 'Append to existing body instead of overwriting it. Default is false.'
    required: false
    default: 'false'
outputs:
  url:
    description: 'URL to the Release HTML Page'
  id:
    description: 'Release ID'
  upload_url:
    description: 'URL for uploading assets to the release'
  assets:
    description: 'JSON array containing information about each uploaded asset, in the format given [here](https://docs.github.com/en/rest/reference/repos#upload-a-release-asset--code-samples) (minus the `uploader` field)'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: 'purple'
  icon: 'package'
