name: 'release'

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - id: version
        name: Determine next version
        uses: conventional-actions/next-version@v1
      - name: Create release
        uses: ./
        with:
          tag_name: ${{steps.version.outputs.version}}
